### ISSUE TITLE
port LinageOs to "selene"

### ISSUE THREAD

**Issue by ghost** [hasan6034/recovery_device_xiaomi_selene#1]
Hello, I saw that you have ported some systems such as crDroid, Alpha Droid, Project Sakura to "selene" devices. Could you port LinageOS (for example, android 14) to "selene"?

**Comment by ghost** [comment]
Hey, I recently saw your [lineage build](https://sourceforge.net/projects/hasan6034-builds/files/selene/lineage-21.0-Ext-Community-selene-Gapps-20240606-2030.zip/download). Can you build without Gapps?

**Comment by ghost** [comment]
I'm sorry to ask, when will you finish the full build? (I've already managed to break my system heh)

**Comment by hasan6034** [comment]
@cattmem Can you reach me on telegram
